#ifndef PIPELINE_FRAMEGRAPH_GLSL
#define PIPELINE_FRAMEGRAPH_GLSL

#include "/pipeline/resources.glsl"

#define FOXY_STAGE_PREPARE_SKY_LUT 100
#define FOXY_STAGE_PREPARE_CLOUD_COVERAGE 110
#define FOXY_STAGE_SSPT_TRACE 150
#define FOXY_STAGE_SSPT_TEMPORAL 160
#define FOXY_STAGE_SSPT_DENOISE_NEAR 165
#define FOXY_STAGE_SSPT_DENOISE_WIDE 168
#define FOXY_STAGE_SSPT_COMPOSITE 170
#define FOXY_STAGE_CLOUD_SOURCE 200
#define FOXY_STAGE_CLOUD_RESOLVE 210
#define FOXY_STAGE_WATER_COMPOSITE 300
#define FOXY_STAGE_VOLUMETRIC_SOURCE 310
#define FOXY_STAGE_VOLUMETRIC_RESOLVE 320
#define FOXY_STAGE_TEMPORAL_BOUNDARY 400
#define FOXY_STAGE_BLOOM_PREFILTER 500
#define FOXY_STAGE_BLOOM_BLUR_X 510
#define FOXY_STAGE_BLOOM_BLUR_Y 520
#define FOXY_STAGE_TAA_SLOT_RESERVED 600
#define FOXY_STAGE_FINAL_PRESENT 900

#define FOXY_STAGE_RAY_SIGNAL_CURRENT FOXY_STAGE_SSPT_TRACE
#define FOXY_STAGE_RAY_SIGNAL_HISTORY FOXY_STAGE_SSPT_TEMPORAL
#define FOXY_STAGE_VOXEL_UNALLOCATED 0

#endif
