#ifndef FOXY_SETTINGS_GLSL
#define FOXY_SETTINGS_GLSL

#if defined(DISTANT_HORIZONS) || defined(LOD_MOD_ACTIVE) || defined(VOXY)
#define FOXY_DH_ACTIVE 1
#else
#define FOXY_DH_ACTIVE 0
#endif

#if defined(VOXY)
#define FOXY_DIRECT_SHADOW_BRIDGE_ACTIVE 1
#elif defined(FOXY_DIM_NETHER) || defined(FOXY_DIM_END)
#define FOXY_DIRECT_SHADOW_BRIDGE_ACTIVE 0
#else
#define FOXY_DIRECT_SHADOW_BRIDGE_ACTIVE 1
#endif

#define FOXY_WATER_SSR_NORMAL_STABILIZATION 1
#define FOXY_WATER_SSR_TEMPORAL_STABILIZATION 1

#define FOXY_EXPOSURE 1.0
#define FOXY_AUTO_EXPOSURE 1.0
#define FOXY_AUTO_EXPOSURE_DARK_LIMIT 2.0
#define FOXY_POST_EXPOSURE_BRIGHTNESS 1.0
#define FOXY_SUN_INTENSITY 1.15
#define FOXY_MOON_INTENSITY 0.12
#define FOXY_AMBIENT_INTENSITY 0.65
#define FOXY_SKY_AMBIENT_NEUTRALITY 0.70
#define FOXY_SKY_AMBIENT_LIFT 1.15
#define FOXY_PBR 1
#define FOXY_PBR_SPECULAR_MAPS 1
#define FOXY_PBR_NORMAL_MAPS 1
#define FOXY_PBR_TEXTURE_FORMAT 0

#define FOXY_PBR_EMISSION_BRIGHTNESS 6.0
#define FOXY_SSPT_PBR_EMISSION_BRIGHTNESS 2.0
#define FOXY_PBR_SPECULAR_STRENGTH 1.25
#define FOXY_PBR_FALLBACK_F0 0.035
#define FOXY_PBR_LIGHT_ANGULAR_RADIUS 0.00465
#define FOXY_PBR_SPECULAR_CLAMP 4.0
#define FOXY_PBR_METAL_DIFFUSE 0.30
#define FOXY_PBR_SSS 1
#define FOXY_PBR_SSS_INTENSITY 1.0
#define FOXY_PBR_SSS_ALPHA_NEIGHBORS 0
#define FOXY_PBR_SSS_SHEEN 1
#define FOXY_PBR_PARALLAX 0
#define FOXY_PBR_PARALLAX_DEPTH 0.25
#define FOXY_PBR_PARALLAX_STEPS 16
#define FOXY_PBR_PARALLAX_DISTANCE 24.0
#define FOXY_MATERIAL_REFLECTIONS 0

#define FOXY_MATERIAL_REFLECTION_HIGH_QUALITY 0
#define FOXY_MATERIAL_REFLECTION_GLOBAL 0
#define FOXY_MATERIAL_REFLECTION_STEPS 12
#define FOXY_MATERIAL_REFLECTION_STRENGTH 1.0
#define FOXY_MATERIAL_REFLECTION_ROUGHNESS_CUTOFF 0.72

#define FOXY_MATERIAL_REFLECTION_MIN_SMOOTHNESS 0.34
#define FOXY_MATERIAL_REFLECTION_ENERGY_THRESHOLD 0.01
#define FOXY_MATERIAL_REFLECTION_ENERGY_ROUGHNESS_ATTENUATION 2.0
#define FOXY_MATERIAL_REFLECTION_GLOBAL_MIN_ENERGY 0.025
#define FOXY_ATMOSPHERE_STYLE 2
#define FOXY_SUN_ANGULAR_RADIUS 0.0218
#define FOXY_SUN_DISK_BRIGHTNESS 520.0
#define FOXY_SKY_SCATTER_EXPOSURE 0.15
#define FOXY_SKY_HORIZON_WHITE 0.15
#define FOXY_SKY_HORIZON_WHITE_RANGE 0.72
#define FOXY_SKY_BLUE_DEPTH 1.0
#define FOXY_SKY_SUNSET_WARMTH 1.0
#define FOXY_SKY_SUNSET_HORIZON_OFFSET 400.0
#define FOXY_SKY_SUNRISE_HORIZON_OFFSET 0.0
#define FOXY_SKY_SOLAR_SUNSET_HORIZON_OFFSET 400.0
#define FOXY_SKY_SOLAR_SUNRISE_HORIZON_OFFSET 0.0
#define FOXY_SKY_TWILIGHT_SCALE 1.0
#define FOXY_SKY_VANILLA_CELESTIALS 0
#define FOXY_SKY_VANILLA_MOON 1
#define FOXY_NASA_GALAXY 1
#define FOXY_NASA_GALAXY_INTENSITY 0.25
#define FOXY_FOG_DENSITY 0.30
#define FOXY_FOG_BLUE_SHIFT 1.0
#define FOXY_FOG_START 0.50
#define FOXY_WORLD_FOG_STRENGTH 0.25
#define FOXY_WORLD_FOG_HEIGHT 72.0
#define FOXY_WORLD_FOG_FALLOFF 96.0
#define FOXY_AIR_AEROSOL_ENABLED 1
#define FOXY_AIR_AEROSOL_DENSITY 0.16
#define FOXY_AIR_AEROSOL_FADE_START 72.0
#define FOXY_AIR_AEROSOL_FADE_END 384.0
#define FOXY_AIR_MOLECULAR_ENABLED 1
#define FOXY_AIR_MOLECULAR_DENSITY 0.16
#define FOXY_AIR_MOLECULAR_FADE_START 72.0
#define FOXY_AIR_MOLECULAR_FADE_END 1088.0
#define FOXY_AIR_DENSITY_NOON 1.0
#define FOXY_AIR_DENSITY_TWILIGHT 1.0
#define FOXY_AIR_DENSITY_NIGHT 1.0
#define FOXY_AIR_TEMPERATURE_TWILIGHT 6500
#define FOXY_AIR_TEMPERATURE_NOON 6500
#define FOXY_VOLUMETRIC_LIGHT 1
#define FOXY_VL_CLUMPY_FOG 1
#define FOXY_VL_QUALITY 1
#define FOXY_VL_STRENGTH 1.20
#define FOXY_VL_RESOLUTION 0.50
#define FOXY_VL_DISTANCE 320.0
#define FOXY_VL_ANISOTROPY 0.62
#define FOXY_VL_SHADOWING 1.0
#define FOXY_VL_SHADOW_DARKEN 2.0
#define FOXY_VL_CLUMPINESS 0.58
#define FOXY_VOLUME_COMPACT_CBR 0
#define FOXY_COLOR_SATURATION 1.0
#define FOXY_COLOR_SHADOW_CURVE 0.08
#define FOXY_COLOR_HIGHLIGHT_CURVE 0.18
#define FOXY_WHITE_BALANCE 6500
#define FOXY_COLOR_GRADING 0.35
#define FOXY_PURKINJE_SHIFT 0.30
#define FOXY_VIGNETTE 0.08
#define FOXY_BLOOM_STRENGTH 15
#define FOXY_BLOOM_THRESHOLD 0.35
#define FOXY_BLOOM_RADIUS 0.85
#define FOXY_BLOOM_FOG 0.25
#define FOXY_MOTION_BLUR 0.45
#define FOXY_TONEMAPPER 2
#define FOXY_CAS 0
#define FOXY_CAS_STRENGTH 0.55
#define FOXY_DOF 0
#define FOXY_DOF_AUTO_FOCUS 1
const float centerDepthHalflife = 1.0;
#define FOXY_DOF_QUALITY 1
#define FOXY_DOF_FOCUS_DISTANCE 12.0
#define FOXY_DOF_APERTURE 1.0
#define FOXY_DOF_MAX_BLUR 6.0
#include "/lib/temporal_options.glsl"

#define FOXY_RAY_AO 0
#define FOXY_RAY_SSGI 1
#define FOXY_RAY_IRC 2
#define FOXY_RAY_VRTGI 3
#define FOXY_RAY_SSPT_VRTGI 4
#define FOXY_RAY_IRC_SSPT 5
#define FOXY_RAY_MODE 0
#if FOXY_RAY_MODE == FOXY_RAY_IRC_SSPT
	#define FOXY_IRC_SSPT_MODE 1
#else
	#define FOXY_IRC_SSPT_MODE 0
#endif
#define FOXY_SSPT_SPP 1
#define FOXY_SSPT_TRACE_STEPS 16
#define FOXY_SSPT_MAX_DISTANCE 48.0
#define FOXY_SSPT_HISTORY_FRAMES 48
#define FOXY_SSPT_DENOISER 1
#define FOXY_SSPT_DENOISE_QUALITY 2
#define FOXY_SSPT_BOUNCE_BRIGHTNESS 8.0
#define FOXY_SSPT_DENOISE_STRENGTH 1.25
#define FOXY_SSPT_MINIMUM_LIGHT 1
#define FOXY_SSPT_MINIMUM_LIGHT_STRENGTH 3.0
#define FOXY_SSPT_EMISSIVE_FEEDBACK 1
#define FOXY_SSPT_EMISSIVE_BRIGHTNESS 1.0

#define FOXY_VXGI_TRUE_SECONDARY_BOUNCE 1
#define FOXY_VRTGI_REALISTIC_MODE 1
#if FOXY_RAY_MODE == FOXY_RAY_IRC
	#define FOXY_IRC_MODE 1
#else
	#define FOXY_IRC_MODE 0
#endif
#define FOXY_VRTGI_RESOLUTION 0.5

#define FOXY_VRTGI_TEMPORAL_INTERLEAVE 1
#define FOXY_IRRADIANCE_CACHE 1
#define FOXY_IRRADIANCE_CACHE_STRENGTH 1.0
#define FOXY_IRRADIANCE_CACHE_SKY_BRIGHTNESS 1.0
#define FOXY_IRRADIANCE_CACHE_BLOCK_BRIGHTNESS 1.0
#define FOXY_IRRADIANCE_CACHE_HISTORY_FRAMES 160
#if FOXY_RAY_MODE == FOXY_RAY_VRTGI || FOXY_RAY_MODE == FOXY_RAY_SSPT_VRTGI
	#define FOXY_RAY_RESOLUTION FOXY_VRTGI_RESOLUTION
#else
	#define FOXY_RAY_RESOLUTION 0.5
#endif
#define FOXY_VXGI_MASTER_CALIBRATION 3.0
#define FOXY_VXGI_SUN_CALIBRATION 2.0
#define FOXY_VXGI_EMITTER_CALIBRATION 3.0
#define FOXY_VOXEL_GI_INTENSITY 1.0
#define FOXY_VOXEL_GI_SPP 1
#define FOXY_VOXEL_GI_DISTANCE_CHUNKS 6
#if FOXY_VOXEL_GI_DISTANCE_CHUNKS == 2
	#define FOXY_VOXEL_GI_MAX_DISTANCE 32.0
	#define FOXY_VOXEL_GRID_SIZE 64
	#define FOXY_VOXEL_GRID_COUNT 262144u
#elif FOXY_VOXEL_GI_DISTANCE_CHUNKS == 4
	#define FOXY_VOXEL_GI_MAX_DISTANCE 64.0
	#define FOXY_VOXEL_GRID_SIZE 128
	#define FOXY_VOXEL_GRID_COUNT 2097152u
#elif FOXY_VOXEL_GI_DISTANCE_CHUNKS == 6
	#define FOXY_VOXEL_GI_MAX_DISTANCE 96.0
	#define FOXY_VOXEL_GRID_SIZE 192
	#define FOXY_VOXEL_GRID_COUNT 7077888u
#elif FOXY_VOXEL_GI_DISTANCE_CHUNKS == 8
	#define FOXY_VOXEL_GI_MAX_DISTANCE 128.0
	#define FOXY_VOXEL_GRID_SIZE 256
	#define FOXY_VOXEL_GRID_COUNT 16777216u
#elif FOXY_VOXEL_GI_DISTANCE_CHUNKS == 10
	#define FOXY_VOXEL_GI_MAX_DISTANCE 160.0
	#define FOXY_VOXEL_GRID_SIZE 320
	#define FOXY_VOXEL_GRID_COUNT 32768000u
#elif FOXY_VOXEL_GI_DISTANCE_CHUNKS == 12
	#define FOXY_VOXEL_GI_MAX_DISTANCE 192.0
	#define FOXY_VOXEL_GRID_SIZE 384
	#define FOXY_VOXEL_GRID_COUNT 56623104u
#elif FOXY_VOXEL_GI_DISTANCE_CHUNKS == 16
	#define FOXY_VOXEL_GI_MAX_DISTANCE 256.0
	#define FOXY_VOXEL_GRID_SIZE 512
	#define FOXY_VOXEL_GRID_COUNT 134217728u
#else
	#error FOXY_VOXEL_GI_DISTANCE_CHUNKS must be 2, 4, 6, 8, 10, 12, or 16.
#endif
#define FOXY_VOXEL_GRID_HALF_SIZE (float(FOXY_VOXEL_GRID_SIZE) * 0.5)
#define FOXY_VOXEL_GI_TRACE_ITERATIONS FOXY_VOXEL_GI_MAX_STEPS
#define FOXY_VOXEL_GI_MAX_STEPS 100
#define FOXY_VOXEL_GI_SUN_DIFFUSE_BRIGHTNESS 1.0
#define FOXY_VOXEL_GI_EMITTER_BRIGHTNESS 1.0
#define FOXY_VOXEL_GI_SKY_BRIGHTNESS 1.5

#define FOXY_PRESENTATION_EXPOSURE_MIN 0.00390625
#define FOXY_PRESENTATION_EXPOSURE_MAX min(max(FOXY_AUTO_EXPOSURE_DARK_LIMIT, 1.0), 64.0)
#define FOXY_PRESENTATION_EXPOSURE_STATE_MIN 0.0030
#define FOXY_PRESENTATION_EXPOSURE_STATE_MAX (FOXY_PRESENTATION_EXPOSURE_MAX * 1.125)
#define FOXY_PRESENTATION_MANUAL_EXPOSURE FOXY_EXPOSURE
#define FOXY_PRESENTATION_AUTO_WEIGHT FOXY_AUTO_EXPOSURE

#define FOXY_PRESENTATION_BASE_POST_EXPOSURE_CALIBRATION 2.0
#if FOXY_RAY_MODE == FOXY_RAY_VRTGI && FOXY_VRTGI_REALISTIC_MODE == 1
	#define FOXY_VRTGI_REALISTIC_ACTIVE 1
	#define FOXY_PRESENTATION_SUN_SCALE 5.0
	#define FOXY_PRESENTATION_SKY_SCALE 4.0
	#define FOXY_PRESENTATION_POST_EXPOSURE_CALIBRATION 1.5
#else
	#define FOXY_VRTGI_REALISTIC_ACTIVE 0
	#define FOXY_PRESENTATION_SUN_SCALE 1.0
	#define FOXY_PRESENTATION_SKY_SCALE 1.0
	#define FOXY_PRESENTATION_POST_EXPOSURE_CALIBRATION 2.0
#endif

float PresentationDayWeight(const in float sunAltitude) {
	#if FOXY_VRTGI_REALISTIC_ACTIVE == 1

		return smoothstep(0.30, 0.60, sunAltitude);
	#else
		return 0.0;
	#endif
}

float PresentationSunScale(const in float sunAltitude) {
	return mix(1.0, FOXY_PRESENTATION_SUN_SCALE, PresentationDayWeight(sunAltitude));
}

float PresentationSkyScale(const in float sunAltitude) {
	return mix(1.0, FOXY_PRESENTATION_SKY_SCALE, PresentationDayWeight(sunAltitude));
}

float PresentationPostExposureCalibration(const in float daylightWeight) {
	return mix(
		FOXY_PRESENTATION_BASE_POST_EXPOSURE_CALIBRATION,
		FOXY_PRESENTATION_POST_EXPOSURE_CALIBRATION,
		clamp(daylightWeight, 0.0, 1.0)
	);
}

#if FOXY_RAY_MODE > 0
	#define FOXY_RAY_ACTIVE 1
#else
	#define FOXY_RAY_ACTIVE 0
#endif
#if FOXY_RAY_MODE == FOXY_RAY_SSGI || FOXY_RAY_MODE == FOXY_RAY_SSPT_VRTGI || FOXY_RAY_MODE == FOXY_RAY_IRC_SSPT
	#define FOXY_SSPT 1
#else
	#define FOXY_SSPT 0
#endif
#if FOXY_RAY_MODE >= FOXY_RAY_IRC
	#define FOXY_VOXEL_GI_ACTIVE 1
#else
	#define FOXY_VOXEL_GI_ACTIVE 0
#endif
#if FOXY_VOXEL_GI_ACTIVE == 1 && FOXY_IRRADIANCE_CACHE == 1
	#define FOXY_IRRADIANCE_CACHE_ACTIVE 1
#else
	#define FOXY_IRRADIANCE_CACHE_ACTIVE 0
#endif
#if FOXY_SSPT == 1
	#define FOXY_SSPT_TRACE_ACTIVE 1
#else
	#define FOXY_SSPT_TRACE_ACTIVE 0
#endif
#if FOXY_RAY_ACTIVE == 1
	#define FOXY_SSPT_TEMPORAL_ACTIVE 1
#else
	#define FOXY_SSPT_TEMPORAL_ACTIVE 0
#endif
#if FOXY_RAY_ACTIVE == 1 || FOXY_MATERIAL_REFLECTIONS == 1
	#define FOXY_PT_GBUFFER_ACTIVE 1
#else
	#define FOXY_PT_GBUFFER_ACTIVE 0
#endif
#define FOXY_RAY_PIPELINE FOXY_RAY_ACTIVE
#if FOXY_VOXEL_GI_ACTIVE == 1
	#define FOXY_VOXEL_ACTIVE 1
	#define FOXY_VOXEL_SPACE 1
	const float voxelDistance = FOXY_VOXEL_GI_MAX_DISTANCE;
#else
	#define FOXY_VOXEL_ACTIVE 0
	#define FOXY_VOXEL_SPACE 0
#endif
#if FOXY_RAY_MODE == FOXY_RAY_VRTGI || FOXY_RAY_MODE == FOXY_RAY_SSPT_VRTGI
	#define FOXY_VOXEL_TRACING 1
#else
	#define FOXY_VOXEL_TRACING 0
#endif

#if FOXY_RAY_ACTIVE == 1
	const float ambientOcclusionLevel = 0.0;
#else
	const float ambientOcclusionLevel = 1.0;
#endif

#define FOXY_CLOUDS 1
#define FOXY_CLOUD_QUALITY 0
#define FOXY_CLOUD_STEPS 40
#define FOXY_CLOUD_LIGHT_STEPS 6
#define FOXY_CLOUD_MULTISCATTERING 0
#define FOXY_CLOUD_BLOCK_SHAPE 0
#define FOXY_CLOUD_MEDIUM_DENSITY_SCALE 1.0
#define FOXY_CLOUD_EXTINCTION_SCALE 1.0
#define FOXY_CLOUD_MULTISCATTER_SCALE 1.0
#define FOXY_CLOUD_COVERAGE 0.40
#define FOXY_CLOUD_DENSITY 1.50
#define FOXY_CLOUD_TEMPERATURE -1.0
#define FOXY_CLOUD_SPEED 0.35
#define FOXY_CLOUD_HEIGHT 520.0
#define FOXY_CLOUD_THICKNESS 2500.0
#define FOXY_CLOUD_RANGE 48000.0
#define FOXY_CLOUD_WORLD_SCALE 0.40
#define FOXY_CLOUD_SHAPE_SCALE 1.0
#define FOXY_CLOUD_BASE_BREAKUP 1.0
#define FOXY_CLOUD_EDGE_SOFTNESS 1.0
#define FOXY_CLOUD_BOTTOM_EROSION_SIZE 1.0
#define FOXY_CLOUD_BOTTOM_RELIEF 1.0
#define FOXY_CLOUD_SHAPE_BASE_SCALE 0.000075
#define FOXY_CLOUD_SHAPE_DETAIL_SCALE 0.001120
#define FOXY_CLOUD_CLOUD_SIZE 0.37
#define FOXY_CLOUD_HORIZONTAL_COVERAGE_BIAS 0.08
#define FOXY_CLOUD_VERTICAL_COVERAGE_BIAS 0.06
#define FOXY_CLOUD_CUMULUS_BIAS 1.0
#define FOXY_CLOUD_EROSION_SCALE 3.0
#define FOXY_CLOUD_BOTTOM_DENSITY_POWER 0.88
#define FOXY_CLOUD_VERTICAL_SHEAR 0.0
#define FOXY_CLOUD_HEIGHT_GRADIENT_SCALE 2.48
#define FOXY_CLOUD_HEIGHT_GRADIENT_CONTRAST 1.37
#define FOXY_CLOUD_TOP_LIMIT 2.0
#define FOXY_CLOUD_HARD_HEIGHT_LIMIT 3.0
#define FOXY_CLOUD_RENDER_RANGE_SCALE 1.0
#define FOXY_CLOUD_SHADOW_STRENGTH 0.0
const float sunPathRotation = -28.0;
#define FOXY_SUN_PATH_ROTATION sunPathRotation
#define FOXY_SHADOW_FILTERING 1
#define FOXY_SHADOW_QUALITY 0
#define FOXY_SHADOW_RESOLUTION 1024
#define FOXY_SHADOW_DISTANCE 160.0
#define FOXY_SHADOW_STRENGTH 1.0
#define FOXY_SHADOW_SOFTNESS 0.25
#define FOXY_SHADOW_WARP 0.88
#define FOXY_SHADOW_AMBIENT_DARKEN 0.32
#if FOXY_SHADOW_QUALITY <= 0
	#define FOXY_SHADOW_BLOCKER_SAMPLES 4
	#define FOXY_SHADOW_BLOCKER_BASE_SAMPLES 4
	#define FOXY_SHADOW_FILTER_SAMPLES 8
#elif FOXY_SHADOW_QUALITY == 1
	#define FOXY_SHADOW_BLOCKER_SAMPLES 6
	#define FOXY_SHADOW_BLOCKER_BASE_SAMPLES 4
	#define FOXY_SHADOW_FILTER_SAMPLES 12
#else
	#define FOXY_SHADOW_BLOCKER_SAMPLES 8
	#define FOXY_SHADOW_BLOCKER_BASE_SAMPLES 4
	#define FOXY_SHADOW_FILTER_SAMPLES 16
#endif
#define FOXY_WATER_REFLECTION 0.65
#define FOXY_WATER_REFLECTION_STRETCH 0.55
#define FOXY_WATER_SUN_GLINT 1.0
#define FOXY_WATER_UNDERWATER 0.65
#define FOXY_UNDERWATER_VL_STRENGTH 2.0
#define FOXY_WATER_FOG 0.75
#define FOXY_WATER_DENSITY 1.0
#define FOXY_WATER_SCATTER_BRIGHTNESS 0.25
#define FOXY_WATER_UNDERWATER_DIRECT_LIGHT 0.20
#define FOXY_WATER_ABOVE_DIRECT_LIGHT 0.70
#define FOXY_WATER_CAUSTICS 0
#define FOXY_WATER_CAUSTICS_BRIGHTNESS 0.65
#define FOXY_WATER_SPECTRUM_WAVES 1
#define FOXY_WATER_SPECTRUM_SCALE 1.0
#define FOXY_WATER_SPECTRUM_VERTEX_HEIGHT 2.0
#define FOXY_WATER_SPECTRUM_VERTEX_ANCHOR 0.60
#define FOXY_WATER_SPECTRUM_LARGE_SCALE 3.0
#define FOXY_WATER_SPECTRUM_LARGE_HEIGHT 6.0
#define FOXY_WATER_SPECTRUM_MID_SCALE 3.0
#define FOXY_WATER_SPECTRUM_MID_HEIGHT 1.50
#define FOXY_WATER_SPECTRUM_FINE_SCALE 1.50
#define FOXY_WATER_SPECTRUM_FINE_HEIGHT 0.75
#define FOXY_WATER_SPECTRUM_WARP 0.75
#define FOXY_WATER_SPECTRUM_NORMAL_DETAIL 1.0
#define FOXY_WATER_WAVE_STRENGTH 0.55
#define FOXY_WATER_WAVE_SPEED 1.75
#define FOXY_WATER_NORMAL_AA_STRENGTH 1.0
#define FOXY_WATER_OPT_FAST_REFLECTION_TRACE 0
#define FOXY_WATER_OPT_SKIP_REFLECTION_REFINE 0
#define FOXY_WATER_OPT_FAST_SHADOW 0
#define FOXY_WATER_OPT_FAST_WAVE_NORMAL 0

#define FOXY_SKY_LUT_WIDTH 256.0
#define FOXY_SKY_LUT_HEIGHT 192.0

const int shadowMapResolution = FOXY_SHADOW_RESOLUTION;

const bool shadowHardwareFiltering1 = true;
#if FOXY_SHADOW_FILTERING == 0
const bool shadowtex0Nearest = true;
const bool shadowtex1Nearest = true;
#else
const bool shadowtex0Nearest = false;
const bool shadowtex1Nearest = false;
#endif
#if FOXY_VOXEL_ACTIVE == 1
const float shadowDistance = max(
	FOXY_SHADOW_DISTANCE,
	FOXY_VOXEL_GI_MAX_DISTANCE
);
#else
const float shadowDistance = FOXY_SHADOW_DISTANCE;
#endif
const float shadowDistanceRenderMul = 1.0;

#endif
