#ifndef TEMPORAL_OPTIONS_GLSL
#define TEMPORAL_OPTIONS_GLSL

#define FOXY_TAA_ENABLED 1
#define FOXY_TAAU 0
#define FOXY_TAAU_RENDER_SCALE 0.77
#define FOXY_TAA_JITTER_SCALE 0.125
#define FOXY_TAA_HISTORY_WEIGHT 0.86
#define FOXY_TAAU_HISTORY_WEIGHT 0.89
#define FOXY_TAA_CHROMA_LIMIT 0.08
#define FOXY_TAA_SHARPEN 0.04

#if FOXY_TAA_ENABLED == 1 && FOXY_TAAU == 1
	#define FOXY_TAAU_ACTIVE 1
#else
	#define FOXY_TAAU_ACTIVE 0
#endif

#define FOXY_POST_RESOLVE_ACTIVE 0

#if FOXY_TAA_ENABLED == 1
	#define FOXY_TEMPORAL_JITTER_ACTIVE 1
#else
	#define FOXY_TEMPORAL_JITTER_ACTIVE 0
#endif

#endif
