#version 430

#define FOXY_SSPT_ATROUS_GROUP_SIZE 8
#define FOXY_SSPT_ATROUS_PASS 4
#define FOXY_SSPT_ATROUS_STEP 16
#define FOXY_SSPT_ATROUS_SHARED 0
#define FOXY_SSPT_ATROUS_FULL_KERNEL
#define FOXY_SSPT_ATROUS_BOOTSTRAP_INPUT
#include "/entry/deferred/sspt_atrous.csh"
